PuertoNet/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainApp.urls')),
    path('tinymce/', include('tinymce.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PuertoXperience/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainApp.urls')),
]

mainApp/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from mainApp.views import *
from . import views

urlpatterns = [
    path('', inicio.as_view(), name="inicio"),
    path('Inicio',inicio.as_view(),name='inicio'),
    path('Blogs',BlogsPagina.as_view(),name='Blogs'),
    path('Cursos',cursos.as_view(),name='Cursos'),
    path('cursosOrden',cursosOrden.as_view(),name='cursosOrden'),
    path('Historia',historia.as_view(),name='Historia'),
    path('AvisoDePrivacidad',avisoprivacidad.as_view(),name='AvisoDePrivacidad'),
    path('TerminosYcondiciones',terminoscondiciones.as_view(),name='TerminosYcondiciones'),
    path('Soporte',soporte.as_view(),name='Soporte'),
	# path('play-video', views.play_video, name="play-video"),
    path('accounts/',include ('allauth.urls')),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.signout, name='logout'),
    path('play-video/<str:vid_id>/', play_video.as_view(), name='play-video'),
    path('reply-comment/<str:vid_id>/<int:comment_id>/', ReplyComment.as_view(), name='reply-comment'),
    path('conocenos/', views.conocenos, name='Conocenos'),
    path('ComentarioPagina/', views.comentarioPagina, name='ComentarioPagina'),
    
    path('editarUsuario/',views.editarUsuario, name='editarUsuario'),

    path('subirVideo/', views.subirVideo, name='subirVideo'),
    path('subirImagen/', views.subirImagen, name='subirImagen'),
    path('subirBlog/', views.subirBlog, name='subirBlog'),
    path('administrarContenido/', views.administrarContenido, name='administrarContenido'),
    path('notificaciones/', views.notificaciones, name='notificaciones'),
    path('infografias/', views.infografias, name='Infografias'),
    path('detallesInfografias/<int:id>', views.DetallesInfografias.as_view(), name='detallesInfografia'),
    path('reply-comment-info/<int:id>/<int:comment_id>/', ReplyCommentInfo.as_view(), name='reply-comment-info'),
    path('reply-comment-blog/<int:id>/<int:comment_id>/', ReplyCommentBlog.as_view(), name='reply-comment-blog'),    
    path('tinymce/', include('tinymce.urls')),
    path('Blog/<int:blog_id>/', TemplateBlog.as_view(), name='Blog'),
    path('tinymce/', include('tinymce.urls')),
    path('vaciarNotificaciones', views.vaciarNotificaciones, name='vaciarNotificaciones'),
    path('eliminarInfografia/<int:id>', views.EliminarInfografia, name='eliminarInfografia'),
    path('eliminarVideo/<int:id>', views.EliminarVideo, name='eliminarVideo'),
    path('eliminarBlog/<int:id>', views.EliminarBlog, name='eliminarBlog'),
    path('editarBlog/<int:id>/update', views.editarBlog, name='editarBlog'),
    path('infographics/<int:pk>/update/', InfographicsUpdateView.as_view(), name='editarInfografias'),
    path('videos/<int:pk>/update/', LogMultimediaUpdateView.as_view(), name='editarVideos'),
    path('subirContenido/',views.subirContenido,name='subirContenido'),

    
    

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mainApp/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    video_id = models.CharField(max_length=20)
    text = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    parent_comment = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.username} - {self.timestamp}'
    
class ComentariosPagina(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.username} - {self.timestamp}'
    
class Blogs(models.Model):
    titulo = models.TextField()
    imagenPortada = models.ImageField(upload_to='static/assets/img/blogs/')  # Ruta relativa a tu directorio de aplicaciones
    introduccion = models.TextField()
    contenido = models.TextField()
    autor = models.TextField(null=True, blank=True)  # Permitir nulo o configurar un valor predeterminado
    fecha = models.DateTimeField(default=datetime.now)
    def __str__(self):
            return f'{self.titulo} '
    
category=[0,'Admin'],[1,'Usuario']
class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(null=True,blank=True, upload_to='profile/')
    type_user=models.IntegerField(choices=category, default="1")
    def __str__(self):
        mapping_tipo_usuario = dict(category)
        tipo_usuario_str = mapping_tipo_usuario.get(self.type_user, 'Desconocido')
        return f'{self.user.username} - {tipo_usuario_str}'
    
FormatCategory=[0,'Imagen'],[1,'Video'] 
CourseCategory=[0,'General'],[1,'Principiantes'],[3,'Kids'] 
class Infographics(models.Model):
        user = models.ForeignKey(User, on_delete=models.CASCADE)
        title = models.CharField(max_length=255)
        description = models.TextField()
        format = models.IntegerField(choices=FormatCategory, default="0")
        file = models.FileField(upload_to='files/')
        category = models.IntegerField(choices=CourseCategory, default="0")
        supplementary_videos = models.ManyToManyField('LogMultimedia', blank=True)
        supplementary_Infographics = models.ManyToManyField('Infographics', blank=True)
        supplementary_Blogs = models.ManyToManyField('Blogs', blank=True)       
        timestamp = models.DateTimeField(auto_now_add=True)
        def nombreCompleto(self):
            texto = "{0} {1}"
            return texto.format(self.user.first_name, self.user.last_name)
    
        def __str__(self):
            return f'{self.title} '
   
class CommentInfo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    info_id = models.ForeignKey( Infographics, on_delete=models.CASCADE)
    text = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    parent_comment = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE)
    def __str__(self):
        return f'{self.user.username} - {self.timestamp}'  

class CommentBlog(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    blog_id = models.ForeignKey( Blogs, on_delete=models.CASCADE)
    text = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    parent_comment = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE)
    def __str__(self):
        return f'{self.user.username} - {self.timestamp}'  

class Notifications(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    admin=models.ForeignKey(
     User,
        on_delete=models.CASCADE, related_name='Supervisor'
    )
       
    
   
class LogMultimedia(models.Model):
    title = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE,null=True)
    video_id = models.CharField(max_length=20)
    category = models.IntegerField(choices=CourseCategory, default="0")
    timestamp = models.DateTimeField(auto_now_add=True)
    supplementary_videos = models.ManyToManyField('LogMultimedia', blank=True)
    supplementary_Infographics = models.ManyToManyField('Infographics', blank=True)
    supplementary_Blogs = models.ManyToManyField('Blogs', blank=True) 
    format = models.IntegerField(choices=FormatCategory, default="1")
    def nombreCompleto(self):
        texto = "{0} {1}"
        return texto.format(self.user.first_name, self.user.last_name)
    def __str__(self):
        return f'{self.title}'

class APIKey(models.Model):
    service_name = models.CharField(max_length=100, unique=True)
    key = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.service_name} API Key"

templates/perfil/menuLateral.html
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<div class="col-2">
    <div class="menuLateral">
        <div class="text-center">
            
            
          
            {% if  user.profile_set.first.image %}
            <img src="{{ user.profile_set.first.image.url}}" alt="Foto de perfil" class="mx-auto" style="width: 50%;">
        {% else %}
        <img src="../../static/assets/img/inicio/user.png" class="mx-auto" style="width: 50%;"/>
        {% endif %}
 
            <h3 style="word-wrap: break-word;" class="nombreUsuario">{{request.user.first_name}} {{request.user.last_name}}</h3>
        </div>
        <ul class="contenedorOpcionesMenuLateral nav flex-column">
            <div class="dropdown-divider" style="height: 0; margin: 0.5rem 0; overflow: hidden; border-top: 1px solid #000000;"></div>
            <li class="itemMenu">
                <a class="opcionesMenu" href="{% url 'editarUsuario' %}"><i class="fa-solid fa-user-pen me-2"></i><span>Mi perfil</span></a>
            </li>
            {% if  user.profile_set.first.type_user == 0 %} 
            {% comment %} <li class="itemMenu">
                <a class="opcionesMenu" href="{% url 'subirVideoImagen' %}"><i class="fa-solid fa-photo-film me-2"></i><span>Subir video / imagen</span></a>
            </li> {% endcomment %}
            <li class="itemMenu">
                <a class="opcionesMenu" href="{% url 'subirContenido' %}"><i class="fa-solid fa-arrow-up-from-bracket me-2"></i><span>Subir contenido</span></a>
            </li>
            <li class="itemMenu">
                <a class="opcionesMenu" href="{% url 'administrarContenido' %}"><i class="fa-solid fa-list me-2"></i><span>Administrar contenido</span></a>
            </li>
            <li class="itemMenu">
                <a class="opcionesMenu" href="{% url 'notificaciones' %}"><i class="fa-solid fa-bell me-2"></i><span>Notificaciones</span></a>
            </li>
            {% comment %} <li class="itemMenu" id="subirVideoImagen">
                <a class="opcionesMenu" href="#">
                    <i class="fa-solid fa-photo-film me-2"></i>
                    <span>Subir contenido</span>
                </a>
                <ul class="submenu">
                    <li><a href="">Subir video</a></li>
                    <li><a href="{% url 'subirImagen' %}">Subir infografía</a></li>
                </ul>
            </li> {% endcomment %}
            
            {% endif %}
            <div class="dropdown-divider" style="height: 0; margin: 0.5rem 0; overflow: hidden; border-top: 1px solid #000000; margin-top: 20px;"></div>
            <li class="itemMenu">
                <a class="opcionesMenu" href="{% url 'Soporte' %}"><i class="fa-solid fa-wrench me-2"></i><span>Soporte</span></a>
            </li>


        </ul>
    </div>
</div>

<script>
    // Script para manejar el clic y mostrar/ocultar el submenú
    $(document).ready(function() {
        $("#subirVideoImagen").on("click", function() {
            $(this).find(".submenu").toggle();
        });
    });
    </script>