PuertoNet/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainApp.urls')),
    path('tinymce/', include('tinymce.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

PuertoXperience/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainApp.urls')),
]

mainApp/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from mainApp.views import *
from . import views

urlpatterns = [
    path('', inicio.as_view(), name="inicio"),
    path('Inicio',inicio.as_view(),name='inicio'),
    path('Blogs',BlogsPagina.as_view(),name='Blogs'),
    path('Cursos',cursos.as_view(),name='Cursos'),
    path('cursosOrden',cursosOrden.as_view(),name='cursosOrden'),
    path('Historia',historia.as_view(),name='Historia'),
    path('AvisoDePrivacidad',avisoprivacidad.as_view(),name='AvisoDePrivacidad'),
    path('TerminosYcondiciones',terminoscondiciones.as_view(),name='TerminosYcondiciones'),
    path('Soporte',soporte.as_view(),name='Soporte'),
	# path('play-video', views.play_video, name="play-video"),
    path('accounts/',include ('allauth.urls')),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.signout, name='logout'),
    path('play-video/<str:vid_id>/', play_video.as_view(), name='play-video'),
    path('reply-comment/<str:vid_id>/<int:comment_id>/', ReplyComment.as_view(), name='reply-comment'),
    path('conocenos/', views.conocenos, name='Conocenos'),
    path('ComentarioPagina/', views.comentarioPagina, name='ComentarioPagina'),
    
    path('editarUsuario/',views.editarUsuario, name='editarUsuario'),

    path('subirVideo/', views.subirVideo, name='subirVideo'),
    path('subirImagen/', views.subirImagen, name='subirImagen'),
    path('subirBlog/', views.subirBlog, name='subirBlog'),
    path('administrarContenido/', views.administrarContenido, name='administrarContenido'),
    path('notificaciones/', views.notificaciones, name='notificaciones'),
    path('infografias/', views.infografias, name='Infografias'),
    path('detallesInfografias/<int:id>', views.DetallesInfografias.as_view(), name='detallesInfografia'),
    path('reply-comment-info/<int:id>/<int:comment_id>/', ReplyCommentInfo.as_view(), name='reply-comment-info'),
    path('reply-comment-blog/<int:id>/<int:comment_id>/', ReplyCommentBlog.as_view(), name='reply-comment-blog'),    
    path('tinymce/', include('tinymce.urls')),
    path('Blog/<int:blog_id>/', TemplateBlog.as_view(), name='Blog'),
    path('tinymce/', include('tinymce.urls')),
    path('vaciarNotificaciones', views.vaciarNotificaciones, name='vaciarNotificaciones'),
    path('eliminarInfografia/<int:id>', views.EliminarInfografia, name='eliminarInfografia'),
    path('eliminarVideo/<int:id>', views.EliminarVideo, name='eliminarVideo'),
    path('eliminarBlog/<int:id>', views.EliminarBlog, name='eliminarBlog'),
    path('editarBlog/<int:id>/update', views.editarBlog, name='editarBlog'),
    path('infographics/<int:pk>/update/', InfographicsUpdateView.as_view(), name='editarInfografias'),
    path('videos/<int:pk>/update/', LogMultimediaUpdateView.as_view(), name='editarVideos'),
    path('subirContenido/',views.subirContenido,name='subirContenido'),

    
    

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mainApp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Blogs, Profile, Infographics
from tinymce.widgets import TinyMCE
from .models import Profile, LogMultimedia

class CommentForm(forms.Form):
    text = forms.CharField( widget=forms.Textarea(attrs={
            'class': 'form-control',
            'name': 'comentario',
            'placeholder': 'Cuéntanos tu opinión',
            'aria-label': 'With textarea',
            'rows': 2, 'cols': 30
        }))
class BlogForm(forms.ModelForm):
    class Meta:
        model = Blogs
        fields = ['titulo', 'imagenPortada', 'introduccion', 'contenido','autor']

    widgets = {
        'titulo': forms.TextInput(attrs={'class': 'form-control'}),
        'imagenPortada': forms.FileInput(attrs={'class': 'form-control'}),
        'introduccion': forms.TextInput(attrs={'class': 'form-control'}),
        'contenido': TinyMCE(attrs={'class': 'form-control', 'rows': 10}),
        'autor': forms.TextInput(attrs={'class': 'form-control'}),
    }
    

class CustomUserCreationForm(UserCreationForm):
    name = forms.CharField(max_length=150, required=True)
    lastname = forms.CharField(max_length=150, required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'name', 'lastname', 'password1', 'password2']
        
class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        self.fields['image'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Selecciona una imagen'})
        
class LogImagenForm(forms.ModelForm):
    title = forms.CharField(max_length=255, widget=forms.TextInput(attrs={'class': 'form-control'}))
    description = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 3}))
    file = forms.FileField(widget=forms.ClearableFileInput(attrs={'class': 'form-control'}))

    

    class Meta:
        model = LogMultimedia
        fields = ['file', 'category', 'supplementary_videos', 'supplementary_Infographics','supplementary_Blogs']
        widgets = {
                'category': forms.Select(attrs={'class': 'form-select'}),
                'supplementary_videos': forms.CheckboxSelectMultiple(),
                'supplementary_Infographics': forms.CheckboxSelectMultiple(),
                'supplementary_Blogs': forms.CheckboxSelectMultiple(),
            }
        
        

class LogVideoForm(forms.ModelForm):
    class Meta:
        model = LogMultimedia
        fields = ['title', 'video_id', 'supplementary_videos', 'category', 'supplementary_Infographics', 'supplementary_Blogs']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'video_id': forms.TextInput(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-select'}),
            'supplementary_videos': forms.CheckboxSelectMultiple(),
            'supplementary_Infographics': forms.CheckboxSelectMultiple(),
            'supplementary_Blogs': forms.CheckboxSelectMultiple(),
        }
class EditInfographicsForm(forms.ModelForm):
    description = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 3}))

    class Meta:
        model = Infographics
        fields = ['title', 'file','category', 'description','supplementary_videos', 'supplementary_Infographics', 'supplementary_Blogs']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
                # description = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control', 'rows': 3}))
            'supplementary_videos': forms.CheckboxSelectMultiple(),
            'supplementary_Infographics': forms.CheckboxSelectMultiple(),
            'supplementary_Blogs': forms.CheckboxSelectMultiple(),
        }
 

class EditLogMultimediaForm(forms.ModelForm):
    class Meta:
        model = LogMultimedia
        fields = ['title',  'video_id', 'category', 'supplementary_videos', 'supplementary_Infographics', 'supplementary_Blogs']
        widgets = {
            'supplementary_videos': forms.CheckboxSelectMultiple(),
            'supplementary_Infographics': forms.CheckboxSelectMultiple(),
            'supplementary_Blogs': forms.CheckboxSelectMultiple(),
        }

templates/perfil/editarUsuario/editarUsuario.html
{% extends '../../menu.html' %}

{% load static %}

{% block content %}


<section class="seccionPerfil">
    <div class="container-fluid">
        <div class="row">

            <!-- Menú lateral -->
            {% include '../menuLateral.html' %}

            <!-- Contenido -->
            <div class="col-10">
                <div class="tituloPerfil text-center">
                    <h1 style="color: #357678;">Perfil de usuario</h1>

                    
                </div>
                <br>
                <div class="contenidoEditarUsuario">
                    <form id="ItemForm" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}

                        <h3>Información básica:</h3>
                        <label for="id_name">Nombre:</label><br>
                        <input class="form-control" type="text" name="name" id="name" maxlength="150" required value="{{user.first_name}}"> <br>
                        
                        <label for="id_lastname">Apellidos:</label><br>
                        <input class="form-control" type="text" name="lastname" id="lastname" maxlength="150" required value="{{user.last_name}}"><br>
                        
                        <label for="id_email">Email:</label><br>
                        <input class="form-control" type="email" name="email" id="email" maxlength="254" required value="{{user.email}}"><br>

                        <h3>Añadir ó cambiar imágen de perfil:</h3>
                        <input type="file" class="form-control" name="image" id="image" accept="image/*" ><br>
                    
                        <h3>Cambio de contraseña:</h3>
                        <label for="id_password1">Nueva contraseña:</label><br>
                        <input type="password" class="form-control" name="password1" id="password1"><br>
                        
                        <label for="id_password2">Confirmar contraseña:</label><br> 
                        <input type="password" class="form-control" name="password2" id="password2" ><br>

                        <div class="mx-auto text-center">
                        <button type="submit" class="btn-Acciones" style="margin-top: 10px;">Guardar</button><br>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>



</section>

{% if messages %}
{% for message in messages %}
<div class= {% if message.tags == 'alert-success' %} "alert alert-success alerta alert-dismissible fade show shadow custom-messages fixed-bottom" {% else %} "alert alert-danger alerta  alert-dismissible fade show shadow custom-messages fixed-bottom" {% endif %}>
    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        {{ message }} 
    </div>
{% endfor %}
{% endif %}





{% include '../../footer.html' %}

{% endblock %}